export const layouts = [
    [
        { code: 'Backquote', symbol: '`' },
        { code: 'Digit1', symbol: '1' },
        { code: 'Digit2', symbol: '2' },
        { code: 'Digit3', symbol: '3' },
        { code: 'Digit4', symbol: '4' },
        { code: 'Digit5', symbol: '5' },
        { code: 'Digit6', symbol: '6' },
        { code: 'Digit7', symbol: '7' },
        { code: 'Digit8', symbol: '8' },
        { code: 'Digit9', symbol: '9' },
        { code: 'Digit0', symbol: '0' },
        { code: 'Minus', symbol: '-' },
        { code: 'Equal', symbol: '=' },
        { code: 'Backspace', symbol: 'Backspace', width: 2 },
    ],
    [
        { code: 'Backquote', symbol: 'ё' },
        { code: 'Digit1', symbol: '1' },
        { code: 'Digit2', symbol: '2' },
        { code: 'Digit3', symbol: '3' },
        { code: 'Digit4', symbol: '4' },
        { code: 'Digit5', symbol: '5' },
        { code: 'Digit6', symbol: '6' },
        { code: 'Digit7', symbol: '7' },
        { code: 'Digit8', symbol: '8' },
        { code: 'Digit9', symbol: '9' },
        { code: 'Digit0', symbol: '0' },
        { code: 'Minus', symbol: '-' },
        { code: 'Equal', symbol: '=' },
        { code: 'Backspace', symbol: 'Backspace', width: 2 },
    ],
];
